---
title: "Example Case for Review Paper Figure 2"
output:
  html_document:
    df_print: paged
---

```{r read data}
gtex_prostate <- read.table(file = 'gtex_prostate_example_Case.tsv', sep = '\t', header = TRUE)
```


```{r read pcawg_data}
pcawg_prostate <- read.table(file = 'pcawg_rnaseq_prostate_example_case.tsv', sep = '\t', header = TRUE)
```

```{r ensg_counts}
# Only for a sample
gtex_ensg_exp <- aggregate(gtex_prostate$SRR1091645,by=list(ensg=gtex_prostate$X), FUN=sum)
head(gtex_ensg_exp)
```


```{r ensg_counts_pcawg}
# Only for a sample
pcawg_ensg_exp <- aggregate(pcawg_prostate$X40eb0b4a.3863.403f.a90b.919bfa24237e,by=list(ensg=gtex_prostate$X), FUN=sum)
head(pcawg_ensg_exp)
```


```{r difference}
differences_ensg_exp <- setdiff(gtex_ensg_exp,pcawg_ensg_exp)
head(differences_ensg_exp)
```

```{r ignore_zeros}
wo_zero_gtex <- gtex_ensg_exp[!(apply(gtex_ensg_exp, 1, function(y) any(y == 0))),]
wo_zero_pcawg <- pcawg_ensg_exp[!(apply(pcawg_ensg_exp, 1, function(y) any(y == 0))),]

wo_zero_gtex[wo_zero_gtex==0.00] <- NA
wo_zero_pcawg[wo_zero_pcawg ==0.00] <- NA
wo_zero_gtex_2 <- wo_zero_gtex[complete.cases(wo_zero_gtex),]
wo_zero_pcawg_2 <- wo_zero_pcawg[complete.cases(wo_zero_pcawg),]
```

```{r find_same_exp}
library(dplyr)
inner_join(wo_zero_gtex_2, wo_zero_pcawg_2)
```


```{r fig_same_exp}
# graph ENSG00000168214 expression in both condition
library(data.table)
library(ggplot2)
data <- data.frame(
  name=c("GTEx","PCAWG") ,  
  value=c(gtex_ensg_exp[gtex_ensg_exp$ensg %like% "ENSG00000168214",]$x, pcawg_ensg_exp[pcawg_ensg_exp$ensg %like% "ENSG00000168214",]$x)
  )

# AR ENSG: ENSG00000169083
data_diff <- data.frame(
  name=c("GTEx","PCAWG") ,  
  value=c(gtex_ensg_exp[gtex_ensg_exp$ensg %like% "ENSG00000169083",]$x, pcawg_ensg_exp[pcawg_ensg_exp$ensg %like% "ENSG00000169083",]$x)
  )

par(mfrow=c(1,2))
barplot(data$value, col = c("gray", "lightblue"), xlab = c("ENSG00000168214"), ylim =c(0,60), ylab= "TPM Count", names.arg	= c("GTEx", "PCAWG"), density=c(5,5) , angle=c(0,0))

barplot(data_diff$value, col = c("gray", "lightblue"), xlab = c("ENSG00000169083"), ylim =c(0,60), ylab= "TPM Count", names.arg	= c("GTEx", "PCAWG"), density=c(15,15) , angle=c(45,45))

```


``` {r TPM_counts} 

tpm_counts_pcawg_ar <- pcawg_prostate[pcawg_prostate$X %like% "ENSG00000244045",][,1:3]
tpm_counts_gtex_ar <- gtex_prostate[gtex_prostate$X %like% "ENSG00000244045",][,1:3]

#change col names
colnames(tpm_counts_pcawg_ar) <- c("ENSG", "ENST", "TPM")
colnames(tpm_counts_gtex_ar) <- c("ENSG", "ENST", "TPM")

# draw graphs
require(gridExtra)

plot1 <- ggplot(tpm_counts_pcawg_ar, aes(fill=ENST, y=TPM, x=ENSG)) + 
    geom_bar(position="fill", stat="identity") +
  scale_fill_manual(values=c("#69b3a2", "lightpink", "black", "gray", "lightblue")) + theme(legend.position="none")

plot2 <- ggplot(tpm_counts_gtex_ar, aes(fill=ENST, y=TPM, x=ENSG)) + 
    geom_bar(position="fill", stat="identity") +
  scale_fill_manual(values=c("#69b3a2", "lightpink", "black", "gray", "lightblue")) 

grid.arrange(plot1, plot2, ncol=2)
```


