---
title: "Overlap Analysis of Isoform Switching Events in Pan-Cancer Studies "
author: "Tülay Karakulak"
date: "5/16/2021"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GeneSet Analysis

##### As KIRC and KIRP were analyzed under Kidney-RCC in Kahraman study, we have merged those two cancer types in Vitting and Climente-Gonzales studies in our analysis to detect the overlaps. 

```{r, echo=FALSE}
library(ggvenn)
Kahraman_paths <- file.path("/Users/tulaykarakulak/Documents/GitHub/Isoform_Comparison/Overlaps/GeneSets/Kahraman", c("BRCA_cancer","COAD_cancer","KICH_cancer","LIHC_cancer","LUAD_cancer","LUSC_cancer","PRAD_cancer","THCA_cancer","KIRC_cancer"))

Clemente_paths = file.path("/Users/tulaykarakulak/Documents/GitHub/Isoform_Comparison/Overlaps/GeneSets/Clemente", c("BRCA_cancer","COAD_cancer","KICH_cancer","LIHC_cancer","LUAD_cancer","LUSC_cancer","PRAD_cancer","THCA_cancer","KIRC_KIRP_unique_cancer"))

Vitting_paths = file.path("/Users/tulaykarakulak/Documents/GitHub/Isoform_Comparison/Overlaps/GeneSets/Vitting", c("BRCA_cancer","COAD_cancer","KICH_cancer","LIHC_cancer","LUAD_cancer","LUSC_cancer","PRAD_cancer","THCA_cancer","KIRC_KIRP_unique_cancer"))

for (i in 1:9) {
  Kahraman = read.csv(Kahraman_paths[i], header = FALSE)
  Clemente = read.csv(Clemente_paths[i], header = FALSE)
  Vitting = read.csv(Vitting_paths[i], header = FALSE)
  Genelist <- list(
  Kahraman_Study = Kahraman$V1,
  Clemente_Study = Clemente$V1,
  Vitting_Study = Vitting$V1
  )

  print(ggvenn(
  Genelist, 
  fill_color = c("skyblue1", "#EFC000FF", "tomato1"),
  stroke_size = 0.3, set_name_size = 4,text_color = "black", text_size = 2.5
  ) + ggtitle(tail(strsplit(Kahraman_paths[i], split='/')[[1]],1)))
  
  print(intersect(intersect(Kahraman, Clemente), Vitting))
  }
```

## Isoform Switch Analysis

```{r, echo=FALSE}

Kahraman_paths <- file.path("/Users/tulaykarakulak/Documents/GitHub/Isoform_Comparison/Overlaps/IsoSwitch/Kahraman", c("BRCA_cancer","COAD_cancer","KICH_cancer","LIHC_cancer","LUAD_cancer","LUSC_cancer","PRAD_cancer","THCA_cancer","KIRC_cancer"))

Clemente_paths = file.path("/Users/tulaykarakulak/Documents/GitHub/Isoform_Comparison/Overlaps/IsoSwitch/Clemente", c("BRCA_cancer","COAD_cancer","KICH_cancer","LIHC_cancer","LUAD_cancer","LUSC_cancer","PRAD_cancer","THCA_cancer","KIRC_KIRP_unique_cancer"))

Vitting_paths = file.path("/Users/tulaykarakulak/Documents/GitHub/Isoform_Comparison/Overlaps/IsoSwitch/Vitting/", c("BRCA_cancer","COAD_cancer","KICH_cancer","LIHC_cancer","LUAD_cancer","LUSC_cancer","PRAD_cancer","THCA_cancer","KIRC_KIRP_unique_cancer"))

for (i in 1:9) {
  Kahraman = read.csv(Kahraman_paths[i], header = TRUE)
  Clemente = read.csv(Clemente_paths[i], header = TRUE)
  Vitting = read.csv(Vitting_paths[i], header = TRUE)
  Genelist <- list(
  Kahraman_Study = Kahraman$Normal_Isoform_Cancer_Isoform,
  Clemente_Study = Clemente$Normal_Isoform_Cancer_Isoform,
  Vitting_Study = Vitting$Normal_Isoform_Cancer_Isoform
  )

  print(ggvenn(
  Genelist, 
  fill_color = c("skyblue1", "#EFC000FF", "tomato1"),
  stroke_size = 0.3, set_name_size = 4,text_color = "black", text_size = 2.5
  )+ ggtitle(tail(strsplit(Kahraman_paths[i], split='/')[[1]],1)))
  
  print(intersect(intersect(Kahraman, Clemente), Vitting))
  }
  

```

## Normal Isoform Analysis

```{r, echo=FALSE}
library(tidyr)

Kahraman_paths <- file.path("/Users/tulaykarakulak/Documents/PhD/Review/Data_Comparison/ForRVenn/IsoSwitch//Kahraman", c("BRCA_cancer","COAD_cancer","KICH_cancer","LIHC_cancer","LUAD_cancer","LUSC_cancer","PRAD_cancer","THCA_cancer","KIRC_cancer"))

Clemente_paths = file.path("/Users/tulaykarakulak/Documents/PhD/Review/Data_Comparison/ForRVenn/IsoSwitch/Clemente", c("BRCA_cancer","COAD_cancer","KICH_cancer","LIHC_cancer","LUAD_cancer","LUSC_cancer","PRAD_cancer","THCA_cancer","KIRC_KIRP_Clemente"))

Vitting_paths = file.path("/Users/tulaykarakulak/Documents/PhD/Review/Data_Comparison/ForRVenn/IsoSwitch/Vitting/", c("BRCA_cancer","COAD_cancer","KICH_cancer","LIHC_cancer","LUAD_cancer","LUSC_cancer","PRAD_cancer","THCA_cancer","KIRC_KIRP_Vitting"))

for (i in 1:9) {
  Kahraman = read.csv(Kahraman_paths[i], header = TRUE)
  
  Kahraman_Normals <- (Kahraman %>% separate(Normal_Isoform_Cancer_Isoform, c("Normal", "Cancer"),  "_"))[,1][2:length(Kahraman[,1])]
  
  Clemente = read.csv(Clemente_paths[i], header = TRUE)
  
  Clemente_Normals <- (Clemente %>% separate(Normal_Isoform_Cancer_Isoform, c("Normal", "Cancer"),  "_"))[,1][2:length(Clemente[,1])]
  
  Vitting = read.csv(Vitting_paths[i], header = TRUE)
  
  Vitting_Normals <- (Vitting %>% separate(Normal_Isoform_Cancer_Isoform, c("Normal", "Cancer"),  "_"))[,1][2:length(Vitting[,1])]
    
  Genelist <- list(
  Kahraman_Study = unique(Kahraman_Normals),
  Clemente_Study = unique(Clemente_Normals),
  Vitting_Study = unique(Vitting_Normals)
  )

  print(ggvenn(
  Genelist, 
  fill_color = c("skyblue1", "#EFC000FF", "tomato1"),
  stroke_size = 0.3, set_name_size = 4,text_color = "black", text_size = 2.5
  ) + ggtitle(tail(strsplit(Kahraman_paths[i], split='/')[[1]],1)))
  
  
  print(intersect(intersect(Kahraman_Normals, Clemente_Normals), Vitting_Normals))
  }
  
```

## Cancer Isoform Analysis
```{r, echo=FALSE}
library(tidyr)

Kahraman_paths <- file.path("/Users/tulaykarakulak/Documents/PhD/Review/Data_Comparison/ForRVenn/IsoSwitch//Kahraman", c("BRCA_cancer","COAD_cancer","KICH_cancer","LIHC_cancer","LUAD_cancer","LUSC_cancer","PRAD_cancer","THCA_cancer","KIRC_cancer"))

Clemente_paths = file.path("/Users/tulaykarakulak/Documents/PhD/Review/Data_Comparison/ForRVenn/IsoSwitch/Clemente", c("BRCA_cancer","COAD_cancer","KICH_cancer","LIHC_cancer","LUAD_cancer","LUSC_cancer","PRAD_cancer","THCA_cancer","KIRC_cancer"))

Vitting_paths = file.path("/Users/tulaykarakulak/Documents/PhD/Review/Data_Comparison/ForRVenn/IsoSwitch/Vitting/", c("BRCA_cancer","COAD_cancer","KICH_cancer","LIHC_cancer","LUAD_cancer","LUSC_cancer","PRAD_cancer","THCA_cancer","KIRC_cancer"))

for (i in 1:9) {
  Kahraman = read.csv(Kahraman_paths[i], header = TRUE)
  
  Kahraman_Cancer <- (Kahraman %>% separate(Normal_Isoform_Cancer_Isoform, c("Normal", "Cancer"),  "_"))[,2][2:length(Kahraman[,1])]
  
  Clemente = read.csv(Clemente_paths[i], header = TRUE)
  
  Clemente_Cancer <- (Clemente %>% separate(Normal_Isoform_Cancer_Isoform, c("Normal", "Cancer"),  "_"))[,2][2:length(Clemente[,1])]
  
  Vitting = read.csv(Vitting_paths[i], header = TRUE)
  
  Vitting_Cancer <- (Vitting %>% separate(Normal_Isoform_Cancer_Isoform, c("Normal", "Cancer"),  "_"))[,2][2:length(Vitting[,1])]
    
  Genelist <- list(
  Kahraman_Study = unique(Kahraman_Cancer),
  Clemente_Study = unique(Clemente_Cancer),
  Vitting_Study = unique(Vitting_Cancer)
  )

  print(ggvenn(
  Genelist, 
  fill_color = c("skyblue1", "#EFC000FF", "tomato1"),
  stroke_size = 0.3, set_name_size = 4,text_color = "black", text_size = 2.5
  ) + ggtitle(tail(strsplit(Kahraman_paths[i], split='/')[[1]],1)))
  
  
  print(intersect(intersect(Kahraman_Cancer, Clemente_Cancer), Vitting_Cancer))  
  }
  
```



